// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTcVtuAyuVf47RaRQULvB5l35loYIz8LQ',
    appId: '1:296326367524:web:93b542ee11ff18dd974bb1',
    messagingSenderId: '296326367524',
    projectId: 'ecm-project-9a545',
    authDomain: 'ecm-project-9a545.firebaseapp.com',
    storageBucket: 'ecm-project-9a545.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCIS3J9WzIZ4EOQnlioIc_uoZa8PGMp8k',
    appId: '1:296326367524:android:3128aa7663e69c5f974bb1',
    messagingSenderId: '296326367524',
    projectId: 'ecm-project-9a545',
    storageBucket: 'ecm-project-9a545.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYFjtlkF9otqk-gqnWTzIzWfLFKKwpjFY',
    appId: '1:296326367524:ios:4fca46d4e812eb89974bb1',
    messagingSenderId: '296326367524',
    projectId: 'ecm-project-9a545',
    storageBucket: 'ecm-project-9a545.appspot.com',
    iosBundleId: 'com.example.ecm',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYFjtlkF9otqk-gqnWTzIzWfLFKKwpjFY',
    appId: '1:296326367524:ios:4fca46d4e812eb89974bb1',
    messagingSenderId: '296326367524',
    projectId: 'ecm-project-9a545',
    storageBucket: 'ecm-project-9a545.appspot.com',
    iosBundleId: 'com.example.ecm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTcVtuAyuVf47RaRQULvB5l35loYIz8LQ',
    appId: '1:296326367524:web:aea9272ef6e1f435974bb1',
    messagingSenderId: '296326367524',
    projectId: 'ecm-project-9a545',
    authDomain: 'ecm-project-9a545.firebaseapp.com',
    storageBucket: 'ecm-project-9a545.appspot.com',
  );

}