// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTdIVz7Gfn5t76qRep1hpgoyh0pl1L46U',
    appId: '1:209667583537:web:6b0d8c5eaa7e7d9e7fef10',
    messagingSenderId: '209667583537',
    projectId: 'wais-e4d81',
    authDomain: 'wais-e4d81.firebaseapp.com',
    databaseURL: 'https://wais-e4d81-default-rtdb.firebaseio.com',
    storageBucket: 'wais-e4d81.appspot.com',
    measurementId: 'G-V5556SGCJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_CQ-pc4yOqEtnboWrUxQQUwgkJW0HdtM',
    appId: '1:209667583537:android:d8ac599c65aea4c27fef10',
    messagingSenderId: '209667583537',
    projectId: 'wais-e4d81',
    databaseURL: 'https://wais-e4d81-default-rtdb.firebaseio.com',
    storageBucket: 'wais-e4d81.appspot.com',
  );
}
